### ISSUE TITLE
Use serializable proxies when autowiring

### ISSUE THREAD

**Issue by peholmst** [peholmst/vaadin4spring#1]
When a non-serializable bean is injected into a Vaadin component, the bean should be injected as a serializable proxy to make it possible to use session replication. When the Vaadin component is deserialized, the proxy should look up the correct application context and bean to delegate to.

We have to verify that this is working both using automatic tests and in a real session replication environment. Will create a separate issue for that once we have it implemented.

**Comment by peholmst** [comment]
Closing this issue in favor of #154

**Comment by initialflame** [comment]
Are there some news related to this Issue ? Maybe the Time have solved the "deep problems" ?

**Comment by peholmst** [comment]
I don't know whether the Vaadin dev team has done any work on this in the official add-on. The serialization problem would have to be addressed there and I'm not involved in that project.

**Comment by peholmst** [comment]
Apparently, there is some progress being made: https://dev.vaadin.com/ticket/19462
