### ISSUE TITLE
Create multi-module Maven archetype

### ISSUE THREAD

**Issue by peholmst** [peholmst/vaadin4spring#10]
Create a maven archetype for creating new multi-module Vaadin + Spring Boot projects, with a custom theme, a custom widgetset, a module for client side code and an overlay for production mode deployments.

**Comment by GJRTimmer** [comment]
@peholmst Would it be as simple as to modify the original Vaadin maven-archtype which currently creates a 3 module setup. Same maven-archtype which is used within Netbeans/Eclipse ?

- {project}-production
- {project}-ui
- {project}-widgetset

And only changes some basic code to implement Vaadin4Spring ?

**Comment by peholmst** [comment]
To be honest, I've never used the original Vaadin maven archetype, but that sounds about right.

**Comment by ccit-spence** [comment]
Chiming in out of nowhere, I agree the Maven archetype setup is not something we use either.  Our interest in this project is to tie this into Spring Cloud and use Vaadin as a micro-services UI foundation.  A multi module setup seems like added complexity.  

Disclaimer: Very very new to Vaadin.  Could be a reason I am not aware of at the moment for the multi module setup.

**Comment by peholmst** [comment]
Multi module setup is useful if you want to separate your server side code from your client side (GWT) code, or if you are building a modular application where you want to be able to deploy different versions containing different modules, or if you are deploying your application as a WAR and want to use different overlays for development, testing, production, etc. If you do not fall into one of these categories, a single module project is enough. :-)

**Comment by GJRTimmer** [comment]
The current multi module setup which is created by eclipse for example is very handy, especially for project like @ccit-spence is talking about. You still have a single project where you write and build you application but when you want to create your production setup you run the production module with profile and It will compress all javascript and more handy production stuff.

@ccit-spence check out the default maven Vaadin eclipse project setup. I believe it is the latest Vaadin eclipse plugin.

**Comment by ccit-spence** [comment]
@GJRTimmer That does make sense.  Not fully used to the Vaadin build cycle. Was thinking in terms of Spring Boot's needs not factoring in Vaadin's needs.

**Comment by GJRTimmer** [comment]
@ccit-spence I tried it from a spring-boot point of view, but I found it quite hard. While starting with the Vaadin setup and adding spring-boot into it, was a lot faster, because then you don't have to think about a the Vaadin plugin configuration, to have your build automatically build the widgetset and such.

**Comment by peholmst** [comment]
Vaadin is working on archetypes, no need to do them in the context of Vaadin4Spring.
