### ISSUE TITLE
"Vaadin is running in DEBUG MODE" in log

### ISSUE THREAD

**Issue by nfrankel** [peholmst/vaadin4spring#108]
Spring4Vaadin can be configured with vaadin.servlet.params.productionMode=true in the application.propertie. This works as expected. However, since there are actually 2 different servlets, the SpringAwareVaadinServlet and the StaticContentServlet, the second is not configured to read this parameter and displays the "Vaadin is running in DEBUG MODE" message in the log.

This is not serious, but could mislead Ops into filling in unfounded bugs.

**Comment by LukaszByczynski** [comment]
Here is small workaround. Only thing you need to do is add one parameter to application configuration:

````
vaadin.static.servlet.params.productionMode=true
````

**Comment by nfrankel** [comment]
I'll try, thanks!

**Comment by christoph-frick** [comment]
@LukaszByczynski works for me.  thanks!

**Comment by LukaszByczynski** [comment]
IMHO it should be default value for that servlet. I will push pull request later today.
