### ISSUE TITLE
Merging MVP / Simple-MVP

### ISSUE THREAD

**Issue by GJRTimmer** [peholmst/vaadin4spring#121]
The Presenter class is both available within spring-vaadin-mvp and spring-vaadin-simple-mvp.

Anyone a good idea howto combine both and keep the advantages of both ?

**Comment by zkendall** [comment]
These two presenters use very different approaches. What advantages do you want that one is missing?

**Comment by GJRTimmer** [comment]
I want to keep both, but merge them within one artifact MVP.

**Comment by zkendall** [comment]
They're pretty short classes, just merge the code yourself for your own use.

**Comment by GJRTimmer** [comment]
I'm not only looking for my own use, but also to improve the Vaadin4Spring project, forget to mention that this is not really an issue, but more a improvement discussion.

I will create an single mvp artifact setup and submit it for review.

**Comment by peholmst** [comment]
I'm closing this. Both can continue to live as their own modules.
