### ISSUE TITLE
Eventbus Load Performance

### ISSUE THREAD

**Issue by zkendall** [peholmst/vaadin4spring#124]
I've been doing load testing on my project that uses this vaadin4spring. I just came accross this issue and was able to narrow it down to a UI scoped eventbus.

In the following image you can see that I'm using <50% of the heap and the test includes three steps. Ping /ui, logging in, and getting the /ui. I am running 20 children through this script 15 times. So the first hump begins around 225 sessions. Inside the UI, literally everying in UI.init() is commented out. The only thing enabled is an injection of EventBus. When I comment out the eventbus injection or change its scope to APPLICATION, then performance is normal and fast.
![loadtesting](https://cloud.githubusercontent.com/assets/2762875/5685528/e205537a-97ef-11e4-9518-117304fef2ae.png)

I haven't had a lot of time to investigate this specific manifestation of bad-performance. Soon I'm going to try to reproduce it in the mvp-sample and maybe install some metrics in the library to narrow down what the problem might be.

But in the mean time it'd be a lot of help if others could also do some performance testing and investigation.

**Comment by zkendall** [comment]
I've narrowed it down to events being passed by spring security, being propagated by the ApplicationContextEventBroker and just being expensive.

**Comment by zkendall** [comment]
Can we discuss a way that this ApplicationListener can be toggled by applications using the v4s library? That way we don't have to have our own private build with this commented out.

**Comment by peholmst** [comment]
I think we can do this with an annotation. By default, the listener would be disabled and then you'd have to explicitly enable it if you need it. How does this sound?

**Comment by zkendall** [comment]
I think defaulting to disabled is a good idea. What would be annotated though?

**Comment by peholmst** [comment]
I was thinking you could use some kind of annotation to enable the event bus, like @EnableEventBus and then use this annotation to also control whether application events should be propagated. But maybe a simpler solution would be to simply leave out the application listener from the default configuration and let users that need it add it manually to their configurations?

**Comment by peholmst** [comment]
As of 0.0.3.1 and 0.0.4-SNAPSHOT, application context events are not propagated by default. See the EventBus README for details.

**Comment by zkendall** [comment]
Excellent.

BTW; where is "0.0.3.1" defined/used?

**Comment by peholmst** [comment]
And there is a 0.0.3.1 because we use 0.0.3 in customer projects where we cannot use the latest snapshot for various reasons.

**Comment by peholmst** [comment]
Closing for now. If there are still performance issues, the issue can be reopened.
