### ISSUE TITLE
Tomcat 8 and Server Push not working

### ISSUE THREAD

**Issue by knacht-net** [peholmst/vaadin4spring#136]
It just took me an hour to find the releveant comment in the pom.xml of sample project 

If using gradle apply the follwoing: 

https://github.com/spring-projects/spring-boot/issues/2346

This issue is meant as an Info for others

**Comment by GJRTimmer** [comment]
Should be placed on the Wiki

**Comment by knacht-net** [comment]
Moved to wiki.

**Comment by peholmst** [comment]
@knacht-net Thanks!
