### ISSUE TITLE
BeanCreationException

### ISSUE THREAD

**Issue by caritos** [peholmst/vaadin4spring#138]
I'm trying to integrate Spring Boot Vaadin (https://github.com/peholmst/vaadin4spring) with Vaadin's Dashboard Demo Code (https://github.com/vaadin/dashboard-demo). The only thing modification I made was add the annotation "@VaadinUI" in the DashboardUI class. I checked in my code using the branch "integrate-vaadin-dashboard-demo-project".

I get the error message: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor': Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/validation/ParameterNameProvider.

I'm not really sure what the message means. Can somebody explain it and come up with a resolution to the error message.

Gist Error Output:
https://gist.github.com/anonymous/43d602c1105e00d4d7d6

Clone Url:
https://github.com/caritos/pangolin.git

Branch: 
integrate-vaadin-dashboard-demo-project

**Comment by peholmst** [comment]
My guess is there is an older version of the Bean Validation API on your classpath. See http://stackoverflow.com/questions/14730329/jpa-2-0-exception-to-use-javax-validation-package-in-jpa-2-0 for more information.

**Comment by GJRTimmer** [comment]
see them ```pom.xml``` of the security-sample, please add the following dependency to your pom.

```xml
<dependency>
    <groupId>javax.validation</groupId>
    <artifactId>validation-api</artifactId>
    <version>1.1.0.Final</version>
</dependency>
```

After adding this dependency all should work fine.

@closed
