### ISSUE TITLE
Is the ViewScope missing or can't I just find it?

### ISSUE THREAD

**Issue by pesse** [peholmst/vaadin4spring#139]
Hey there,

writing directly from the GWT.create 2015 after a nice presentation of Peter Letho about Vaadin and JavaEE I ran into the following issue:
In vaadin CDI you have the @ViewScoped annotation and a specific view scope to deal with different views inside one UI.
What's the equivalent in vaadin4spring? Did I just miss something? As for now I can only see Session, UI and Prototype scope and nothing of that seems to fit.

Samuel

**Comment by peholmst** [comment]
There is no view scope. One will be added, but I don't know when.

**Comment by peholmst** [comment]
See #147
