### ISSUE TITLE
Move I18N code to spring-vaadin-i18n module

### ISSUE THREAD

**Issue by peholmst** [peholmst/vaadin4spring#143]
It's a bit strange that some I18N code relies in the main spring-vaadin module and some in the spring-vaadin-i18n module. If possible, everything should be moved to spring-vaadin-i18n.

**Comment by GJRTimmer** [comment]
Request assignment

**Comment by peholmst** [comment]
Sure, go ahead. Thanks! :-)

**Comment by GJRTimmer** [comment]
@peholmst There is a reference within <VaadinConfiguration> (spring-vaadin project) which creates an I18N bean by default.

Should we removed it to unlink a dependecy of spring-vaadin-i18n project ?

**Comment by peholmst** [comment]
@GJRTimmer Yes, it should be removed. When using Spring Boot and spring-vaadin-i18n is on the classpath, it should be automatically enabled. When not using Spring Boot, I18N needs to be explicitly enabled using @EnableVaadinI18N.

**Comment by GJRTimmer** [comment]
@peholmst How do you feel about default enabling ```@EnableCompositeMessageSource``` when you enable the ```@EnableVaadinI18N``` I personally would think it should be enabled when ```@EnableVaadinI18N``` is activated.

**Comment by peholmst** [comment]
@GJRTimmer Yes, the composite message source should be enabled by default when the entire I18N module is enabled.

**Comment by GJRTimmer** [comment]
@peholmst It shall be done soon :-)

**Comment by peholmst** [comment]
Thanks for your help!
