### ISSUE TITLE
Clean up development branches

### ISSUE THREAD

**Issue by peholmst** [peholmst/vaadin4spring#148]
Delete all dead development branches and update the active ones to the lastest MASTER version.

**Comment by GJRTimmer** [comment]
Thank you so much, this is great.

**Comment by peholmst** [comment]
Reopening, I haven't done anything yet, but will do shortly. :-)

**Comment by peholmst** [comment]
There, I deleted almost all of them. feature/serialization is an experimental branch where I've been playing around with serialization stuff.
