### ISSUE TITLE
Split between core modules and extra modules?

### ISSUE THREAD

**Issue by peholmst** [peholmst/vaadin4spring#153]
At least the SideBar module and both of the MVP modules could be considered as extra modules of this add-on. Maybe they should be moved under a separate sub-module called spring-vaadin-extras and named in the same way, e.g. spring-vaadin-extras-sidebar?

**Comment by GJRTimmer** [comment]
I would not rename them as *-extras, If I look at the spring-project, you have all these modules, so why not combine it with the philosophy of Vaadin itself:
- Add-ons
  - spring-vaadin-mvp
  - spring-vaadin-simple-mvp
  - spring-vaadin-sidebar
- samples
  - ...
- spring-boot-vaadin (Core Module, no rename required)
- spring-vaadin-core (Core Module)
- spring-vaadin-test  (Core Module)
- spring-vaadin-security (Core module)
- spring-vaadin-i18n (Core module)

I don't know where to put the touchkit, should it be a core or add-on ?

Also I'm going to try to move both mvp artifacts into one see #121

**Comment by peholmst** [comment]
I have to think about this.

**Comment by peholmst** [comment]
The split has been done as of the migration to Vaadin Spring.
