### ISSUE TITLE
Migrate to Vaadin Official Spring support

### ISSUE THREAD

**Issue by peholmst** [peholmst/vaadin4spring#164]
Development on the official Vaadin Spring add-on started today. It is basically a small subset of this add-on (currently only the scopes), but still developed as a separate product. Once the official version is stable, Vaadin4Spring will be migrated to act as an add-on of the official add-on, providing all the features that didn't end up in the official version.

**Comment by GJRTimmer** [comment]
Very nice :+1:

**Comment by peholmst** [comment]
Migration will be done as soon as the official add-on reaches beta-stage (currently in Alpha).

**Comment by peholmst** [comment]
https://github.com/vaadin/spring

**Comment by peholmst** [comment]
The complete migration is not ready yet, but the most central parts have already been migrated so I'm closing this.
