### ISSUE TITLE
Push with Websocket works?

### ISSUE THREAD

**Issue by eiswind** [peholmst/vaadin4spring#169]
HI, I was just playing around and at least in my simple example push works with your library with websocket if I add
```java
@WebListener
public class AtmosphereSessionSupport extends SessionSupport {
}
```

**Comment by GJRTimmer** [comment]
@eiswind Curious to see an actual working sample.

Are you able to provide a fully working class ? 
If possible could you provide an basic working sample ?

**Comment by eiswind** [comment]
@GJRTimmer I will publish the source on github as soon as saturday is here. I'll drop you a link as soon as its online.

**Comment by eiswind** [comment]
@GJRTimmer I just opened a pull request with a working example. Feel free to have a look at it :)

**Comment by GJRTimmer** [comment]
I will look at it this weekend.

**Comment by peholmst** [comment]
Fixed the pull request. In Spring Boot, servlet listeners are registered as ordinary Spring beans.

**Comment by peholmst** [comment]
And web socket pull does indeed seem to work. We should try it out with some more advanced samples as well, though.

**Comment by peholmst** [comment]
Works with the EventBus sample as well, which indicates that at least the scopes work properly.

**Comment by eiswind** [comment]
Nice to learn about the ServletListener. I just stumbled into this "by accident".

**Comment by peholmst** [comment]
@eiswind @GJRTimmer  I want to test this with all the scopes and the security features enabled. If it works as expected, we should document this and maybe even enable the SessionSupport listener by default if server push is enabled.

**Comment by GJRTimmer** [comment]
Go ahead;

@peholmst might it be an idea to create a test for this within the spring-vaadin-test package.

**Comment by peholmst** [comment]
@GJRTimmer The more tests we write, the better. We've (or at least I've) been too lazy in that department during this project. I just don't really know how you'd set up a reliable test for this. Any ideas?
