### ISSUE TITLE
Please make "org.vaadin.spring.boot.config.StaticContentServlet" class public

### ISSUE THREAD

**Issue by Alan47** [peholmst/vaadin4spring#183]
Hi,

I'm trying to set a couple of Vaadin parameters (primarily "productionMode") programmatically. To do so, I have subclassed `SpringAwareVaadinServlet` and annotated it with `@Component`, as indicated in the JavaDocs. This works like a charm. However, I also need to set the productionMode parameter on the static content servlet. I've checked your code, and `VaadinServletConfiguration` seems to work exactly the same way as `StaticContentVaadinServletConfiguration` - the only difference is that I cannot overwrite `StaticContentServlet` because it isn't public.

Questions:
1) Does the `StaticContentServlet` have package visibility on purpose? If so, why?
2) Is there any other way to set the "productionMode" on the static servlet?
3) Does it even make any *difference* on the static servlet if the production mode is set or not?

**Comment by LukaszByczynski** [comment]
You can add parameter to application configuration:

````
vaadin.static.servlet.params.productionMode=true
````

**Comment by Alan47** [comment]
Thanks, but unfortunately I can't do that for various reasons. I need to infer this information from various other sources at startup and set it programmatically.

**Comment by LukaszByczynski** [comment]
You can still set this programmatically at startup using additional arguments to SpringApplicationBuilder()

**Comment by Alan47** [comment]
Okay, I never used that before, I'll check it out, thanks for the pointer.

Still, it seems strange to me why the dynamic Servlet is public and configurable by overriding while the static servlet is not...

**Comment by peholmst** [comment]
The static servlet is IMO an ugly hack that should be replaced with something nicer. I can make it public, but please be aware that it will most likely disappear in the near future.
