### ISSUE TITLE
Compile PUSH Sample Missing license

### ISSUE THREAD

**Issue by GJRTimmer** [peholmst/vaadin4spring#194]
@peholmst Since today I'm unable to compile the PUSH sample, I've got an error stating I'm missing a PRO license for Vaadin Charts 2

```
[ERROR]
[ERROR] ----------------------------------------------------------------------------------------------------------------------
[ERROR] License for Vaadin Charts 2 not found. Go to vaadin.com/pro for more details.
[ERROR] ----------------------------------------------------------------------------------------------------------------------
```

@peholmst any suggestion how to fix this.

**Comment by LukaszByczynski** [comment]
Unfortunately, Vaadin Charts doesn't have possibility to use AGPL license, due limitation of HighCharts license.

**Comment by GJRTimmer** [comment]
@peholmst @LukaszByczynski A license requirement should never block a build, any suggestion on how to fix or bypass it ?

**Comment by LukaszByczynski** [comment]
Generete trail license or ask Vaadin guys for the free pro tools plan. Commercial tools from Vaadin requires valid licence only during compilation. I think PUSH example doesn't need to use this fancy charts.

**Comment by peholmst** [comment]
Sorry, I didn't realize you couldn't use the new Charts without a commercial license. I will remove Charts from the Push sample ASAP. If you can't wait, feel free to do it yourself. :-)

**Comment by GJRTimmer** [comment]
@peholmst I can wait, I will await your removal, I don't know how to change the sample to keep it intact when removing the add-on.

Compilation is possible by excluding the push artifact.
```
mvn clean install -pl !samples/push-sample
```
