### ISSUE TITLE
Publish version 0.0.5 on the Maven central repository?

### ISSUE THREAD

**Issue by Tonix-Tuft** [peholmst/vaadin4spring#202]
I am trying to use the version 0.0.5, which is supposed to be the latest version of the event bus framework, but it seems that it is not published on the Maven central repository.

http://stackoverflow.com/questions/28786579/how-to-use-the-latest-version-of-vaadin4spring-eventbus-framework-with-maven?noredirect=1#comment45862929_28786579

I have cloned the whole `vaadin4spring` repository and run a `mvn clean install` and installed the whole components of the framework successfully.

Anyway, will you publish the version `0.0.5` of the framework on the central repository?

**Comment by peholmst** [comment]
No, it's not published yet since not all the tasks that are planned for that release have been completed yet. See #170 .
