### ISSUE TITLE
UI Provider implementations need to be serializable

### ISSUE THREAD

**Issue by benheilers** [peholmst/vaadin4spring#211]
Similar to https://github.com/peholmst/vaadin4spring/issues/198, I noticed that AbstractSpringAwareUIProvider is not serializable.  This is demonstrated with a very simple application using spring-boot, spring-vaadin, and spring-session.

First a working application:
```
package sample;

import com.vaadin.server.VaadinRequest;
import com.vaadin.ui.Label;
import com.vaadin.ui.UI;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.boot.builder.SpringApplicationBuilder;
import org.vaadin.spring.annotation.VaadinUI;

@SpringBootApplication
@VaadinUI
public class MyUI extends UI {

    public static void main(String[] args) {
        new SpringApplicationBuilder(MyUI.class).build().run(args);
    }

    @Override
    protected void init(VaadinRequest request) {
        this.setContent( new Label("Hello World!") );
    }
}
```

This can be built with the build.gradle file:
```
buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'org.springframework.boot:spring-boot-gradle-plugin:1.2.2.RELEASE'
    }
}

apply plugin: 'java'
apply plugin: 'spring-boot'

repositories {
    mavenCentral()
}

dependencies {

    compile 'org.springframework.boot:spring-boot-starter-web'

    compile 'org.vaadin.spring:spring-boot-vaadin:0.0.4.RELEASE'
    compile 'com.vaadin:vaadin-themes:7.3.10'
    compile 'com.vaadin:vaadin-client-compiled:7.3.10'
}
```

Now to try serializing the HTTP session (such as used by tomcat when starting/stopping, and also by spring-session), just two lines are added to build.gradle:

    compile 'org.springframework.session:spring-session-data-redis:1.0.0.RELEASE'
    runtime 'org.springframework.data:spring-data-redis'

and these lines to the code:

    import org.springframework.session.data.redis.config.annotation.web.http.EnableRedisHttpSession;

    @EnableRedisHttpSession

This causes a NotSerializableException trying to navigate to the page, because:

1. there is a session attribute "com.vaadin.server.VaadinSession.springAwareVaadinServlet" of type VaadinSession

2. VaadinSession has a list of UI providers:
    private LinkedList<UIProvider> uiProviders = new LinkedList<UIProvider>();

3. Note that com.vaadin.server.UIProvider implements Serializable

4. in that list is an instance of SpringAwareUIProvider

5. note that SpringAwareUIProvider has a non-transient field which is not serializable:
    private final WebApplicationContext webApplicationContext;

**Comment by peholmst** [comment]
Yes, this is a known problem. Actually, it is more complicated than just making the UIProvider serializable; all the scoped beans must also be serializable and they have to be reconfigured after deserialization so that backend beans can be reinjected, listeners registered, etc. There is already a ticket for this, #154 , so I'm closing this one as a duplicate.
