### ISSUE TITLE
VaadinSession is never destroyed

### ISSUE THREAD

**Issue by Alan47** [peholmst/vaadin4spring#214]
Hello everyone,

I'm using Vaadin4Spring with Vaadin 7.4.1. My UI is annotated with `@Push(transport = Transport.LONG_POLLING)` and I use the following settings in application.properties:

    server.sessionTimeout=400
    vaadin.servlet.heartbeatInterval=30

(the time units here are seconds, right?)

My servlet code looks like this:

    @Component
    public class MyServlet extends SpringAwareVaadinServlet {
    
	    @Override
	    protected void servletInitialized() throws ServletException {
		    super.servletInitialized();
            // this is called, as it should be
		    System.out.println("Session Destroy Listener attached");
		    this.getService().addSessionDestroyListener(this::handleVaadinSessionDestroyed);
	    }

	    private void handleVaadinSessionDestroyed(final SessionDestroyEvent event) {
            // this is never called!
		    System.out.println("Closing a VaadinSession...");
	    }
    }

The problem is that `handleVaadinSessionDestroyed` is *never* called, no matter how much time elapsed since the last vaadin UI was closed on the client.

I would be grateful for any advice on this, I'm struggling with it since I need to release certain resources on the server when the Vaadin session is closed. Sorry for asking this here (I know this isn't quite the right place), but I don't know where else I could ask this question...

Thanks,

Alan

**Comment by hesara** [comment]
Although I don't have an immediate answer, perhaps a few things to check to dig a bit deeper:
- does disabling push make the cleanup happen or not?
- does cleanup take place if you set vaadin.servlet.closeIdleSessions (or vaadin.servlet.params.closeIdleSessions if using versions older than 1.0.0.beta2 of Vaadin Spring)?
- is VaadinSession.valueUnbound() ever called?
- does the application ever enter VaadinService.fireSessionDestroy(VaadinSession)?

**Comment by Alan47** [comment]
Hi,

thanks for the pointers. I will check them out one by one, fingers crossed that I'll find something...

**Comment by peholmst** [comment]
Since there has not been any activity on this ticket for many months, I'm closing it. Reopen if this is still a problem.
