### ISSUE TITLE
Plans for release of version 0.0.6 supporting the newly released official Spring/Vaadin

### ISSUE THREAD

**Issue by LarsMilland** [peholmst/vaadin4spring#220]
Hi

We have been using the vaadin4spring release 0.0.5 with the security extension, and would like to migrate to the new official Spring/Vaadin integration:

https://vaadin.com/directory#!addon/vaadin-spring

In that migration we would still like to use the security extension from here - but as a release from this project supporting the security extension and the Spring/Vaadin official integration has not been done yet, we would just like to know if that is right around the corner or we should do the implementation our selves?

Best regards
Lars Milland

**Comment by peholmst** [comment]
I very busy with customer projects right now, so at this point, you're probably better of doing the security implementation yourselves.

**Comment by pesse** [comment]
From my experience the 0.0.6-SNAPSHOT version works quite okay with security extension and official vaadin-spring addon. There are some problems with @Secured-Annotation and you should mark your views as UIScope, but besides that it works good in my current project.

**Comment by LukaszByczynski** [comment]
Peter, I think you can release 0.0.6-SNAPSHOT. Issues with spring-security shouldn't block first release that works official Vaadin Spring Add-on.

**Comment by initialflame** [comment]
Hello Peter, Thank you for your work! It would be great if you can release Version 0.0.6. We can't use any Snapshots in our Project and need the Spring-Security Support for the newer Vaadin version. Thx...

**Comment by peholmst** [comment]
I can try to find time to release a version this week. I hope you are aware that Spring Security is currently broken and is being redesigned.

**Comment by peholmst** [comment]
I have now released 0.0.6.RELEASE as-is.

**Comment by rmueller83** [comment]
@peholmst Could you please upload the new version to Maven Central? It is not there yet.

**Comment by peholmst** [comment]
It should be there already. Maybe something is wrong with the sonatype staging. I'll have a look on Monday.

**Comment by rmueller83** [comment]
Sorry, the packages are already there. I confused the switch to the official addon and still searched for spring-boot-vaadin. My fault.
