### ISSUE TITLE
Decouple addons from spring-vaadin

### ISSUE THREAD

**Issue by zkendall** [peholmst/vaadin4spring#222]
Right now the -eventbus addon requires org.vaadin.spring.spring-vaadin. I think only for the class "org.vaadin.spring.util.ClassUtils".

I was hoping to exclude org.vaadin.spring in favor of com.vaadin.spring, but that breaks the ScopedEventBus from initializing.

**Comment by peholmst** [comment]
I'll see what I can do.

**Comment by zkendall** [comment]
Cool. And if you don't take care of it right away, I might have time to do it this weekend.

**Comment by peholmst** [comment]
It looks like I won't have time to work on Vaadin4Spring for at least a week, so by all means, be my guest. :-)

**Comment by zkendall** [comment]
Went into the code to do this and realized it's already been done. It was just because I had pointed my project to the latest release 5, which was before this change has been started.
