### ISSUE TITLE
Addons Sidebar Sample not working

### ISSUE THREAD

**Issue by typophil** [peholmst/vaadin4spring#236]
Hello all,

I might say upfront that I'm new to Java, Spring and Vaadin, so I might as well qualify myself as the _douchebag of the month_ with this question. I wanted to use the addon/sidebar in a project of mine, but using Version `0.0.6.RELEASE` will give me a 500 upon browsing the page and, apart from other output in the exception, this:

    No qualifying bean of type [org.vaadin.spring.sidebar.SideBar] found for dependency

The sample in the repo uses `0.0.7-SNAPSHOT`. But adding that to my `pom.xml` will end up with the IDE being unable to resolve `org.vaadin.spring.sidebar.SideBar`. And I don't have a `.pom` or `.jar` for that version in my maven repository. Only for the `0.0.6.RELEASE`.

I assume that I need to use a newer version of the sidebar when using injection. If so, then the question would be, where do I get it, when using Maven?

Regards,
Phil

**Comment by peholmst** [comment]
I'll have a look next week when I get back from my vacation. It is quite likely something is broken there.

**Comment by typophil** [comment]
Thanks. Don't stress you out, enjoy your vacation. Might as well just be me who's broken. Like, if you add the `@EnableSideBar` annotation to the spring application, things change. There's another error following that one up, but that might be again something that I'm missing out on.

**Comment by typophil** [comment]
Minor Update bevor I'm off into the weekend myself:

    Error creating bean with name 'org.vaadin.spring.sidebar.config.SideBarConfiguration': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: org.vaadin.spring.i18n.I18N org.vaadin.spring.sidebar.config.SideBarConfiguration.i18n;

Is what I get now. Not yet sure if missing a dependency, missing another annotation or if this is finally related to the different versions (with the annotation mentioned above added, I was able to get rid of that error).

**Comment by peholmst** [comment]
It seems to work on my machine. Did you do a priming build of the project before running the demo?

**Comment by typophil** [comment]
Hello,

thanks for getting back to this. Like I said, I'm fairly new to all that and honestly, I don't get the difference between a build and a priming build in relation to the IDE (IntelliJ) I use. I just said build the thing and it failed. So I cleaned the copy of this repo, `cloned` it again, imported the sample again and *e voilà!*: this time it worked. Sorry about that one.

That'll just bring me back to my own project using the sidebar and that injection error that I get. I hope that information didn't get lost, this `Could not autowire field: org.vaadin.spring.i18n.I18N` error is what I get on my own project when I try to run it (even after `clean` and `compile`, the later works without error).

**Comment by peholmst** [comment]
Have you tried adding @EnableI18N to  your application configuration?

**Comment by peholmst** [comment]
Also please have a look at the feature/sidebar_refac branch that I just created. The side bar will be slightly refactored to support multiple implementations of the visual component. The branch contains the old accordion based side bar and a new side bar especially designed for the Valo theme. The design is not quite stable yet, though - there are a few ugly things I'd like to iron out before pushing to master.

**Comment by typophil** [comment]
I've added the annotation and now it works.
Regarding the new branch, that sounds really good, as the Valo theme is the theme I'm currently using/ want to use with the app.

**Comment by peholmst** [comment]
My redesign is now complete and pushed to the master branch. Take a look at the sample application for the Side Bar and especially the ValoSideBarUI (after starting up the app, navigate to http://localhost:8080/valo).

**Comment by peholmst** [comment]
Closing the ticket since the demo app is now working.
