### ISSUE TITLE
SidebarIcon vanishes on @Secured Operations

### ISSUE THREAD

**Issue by 00v3rdr1v3** [peholmst/vaadin4spring#246]
If you add @Secured("ROLE_ADMIN") to AdminOperation in security-sample-shared, the SidebarIcon disappears.

The reason for this is Spring returning a Dynamic Proxy instead of the real, annotated class when applicationContext.getType() is called in **SideBarItemDescriptor**: 

    private Annotation findIconAnnotation() {
        Class<?> type = applicationContext.getType(beanName);
        while (type != null) {
            Annotation[] annotations = type.getDeclaredAnnotations();
            for (Annotation annotation : annotations) {
                if (annotation.annotationType().isAnnotationPresent(SideBarItemIcon.class)) {
                    return annotation;
                }
            }
            type = type.getSuperclass();
        }
        return null;
    }

**Comment by peholmst** [comment]
Thanks for the report. I will fix this.

**Comment by peholmst** [comment]
I can't reproduce this problem. Is it still valid?

**Comment by peholmst** [comment]
Closing. Please reopen if you still have a problem.
