### ISSUE TITLE
How to address SessionFixation

### ISSUE THREAD

**Issue by LarsMilland** [peholmst/vaadin4spring#251]
Hi

In order to ensure no leakage of session data from one user context to another it is good style to clean up sessions when a login is performed. This is usually done in Spring Security by means of its default sessionfixation protection. To have the same functionality with Spring and Vaadin integrated one could perform steps as shown below - taken from login view on the click action of a "Login Button":

                    // storing password in local variable an cleaning edit fields value to avoid having it around after clicking the login button
                    String passwordString = password.getValue();
                    password.clear();

                    //Clean the HTTP session so that no session values leak in to the new logged in user
                    WrappedSession wrappedSession = VaadinService.getCurrentRequest().getWrappedSession();
                    for(String s : wrappedSession.getAttributeNames()) {
                        if(!ATTRIBUTES_WHICH_SURVIVES.contains( s )) {
                            wrappedSession.removeAttribute( s );
                        }
                    }

                    security.login(username.getValue(), passwordString);

                    //Force a new JSESSIONID after login succeed
                    VaadinService.reinitializeSession(VaadinService.getCurrentRequest());

// attributes to leave in session when cleaning it on login
private static List<String> ATTRIBUTES_WHICH_SURVIVES = Arrays.asList(
"SPRING_SECURITY_SAVED_REQUEST",
"springVaadinServlet.lock",                                                                           "com.vaadin.server.VaadinSession.springVaadinServlet");

Maybe this can be worked into the security extension somehow or added to the sample code somehow.

**Comment by peholmst** [comment]
It should now be possible to use Spring's default session fixation protection, although I haven't documented it yet (the shared security demo application should already use this). Will add something similar to the managed security version as well.
