### ISSUE TITLE
VaadinSharedSecurity cannot access to configured sessionAuthenticationStrategy

### ISSUE THREAD

**Issue by gokhanoner** [peholmst/vaadin4spring#254]
When configuring HttpSecurity, VaadinSharedSecurity autowire the sessionAuthenticationStrategy bean, but this is actually not a bean, it's defined internally & always returns null. Please add a note that users need to create a sessionAuthenticationStrategy bean and use it like

    http.sessionManagement()
            	.sessionAuthenticationStrategy(sessionAuthenticationStrategy())

This way, VaadinSharedSecurity caches correct sessionAuthenticationStrategy.

**Comment by peholmst** [comment]
Sample application updated, README still not updated.

**Comment by peholmst** [comment]
README updated.
