### ISSUE TITLE
VaadinSharedSecurity ignored sessionAuthenticationStrategy failures

### ISSUE THREAD

**Issue by gokhanoner** [peholmst/vaadin4spring#255]
While using ConcurrentSessionControlAuthenticationStrategy or other, authentication can fail after successful authentication due to max. session count etc. But VaadinSharedSecurity assign authentication to context after Manager authentication, to after ```sessionAuthenticationStrategy```.

I get max. session error on login page, but if I remove the login link, it access to the page, because authentication is already set to context.

        try {
            logger.debug("Attempting authentication of {}, rememberMe = {}", authentication, rememberMe);
            final Authentication fullyAuthenticated = getAuthenticationManager().authenticate(authentication);
            context.setAuthentication(fullyAuthenticated);
            if (rememberMe) {
                if (hasRememberMeServices()) {
                    logger.debug("Invoking RememberMeServices");
                    getRememberMeServices().loginSuccess(request, response, authentication);
                } else {
                    throw new IllegalStateException("Requested RememberMe authentication but no RememberBeServices are available");
                }
            }
            logger.debug("Invoking session authentication strategy");
            sessionAuthenticationStrategy.onAuthentication(fullyAuthenticated, request, response);
            logger.debug("Invoking authentication success handler");
            vaadinAuthenticationSuccessHandler.onAuthenticationSuccess(fullyAuthenticated);
            return authentication;
        } catch (AuthenticationException e) {
            logger.debug("Authentication failed");
            context = SecurityContextHolder.createEmptyContext();
            if (hasRememberMeServices()) {
                logger.debug("Invoking RememberMeServices");
                getRememberMeServices().loginFail(request, response);
            }
            throw e;
        }
so
 - ```context.setAuthentication(fullyAuthenticated);``` and rememeberMe check needs to be moved after ```sessionAuthenticationStrategy```check
- catch should set authentication to null, instead of setting context to null.

Please see ```AbstractAuthenticationProcessingFilter``` implementation, spring-security call this normally.

**Comment by gokhanoner** [comment]
What I think is, instead of all this, there should be a way to invoke Spring managed authentication: 

If you use form login, or basic authentication, spring-security setup will handle the necessary auth. for us. But here, we' need to call the authentication from server. And You're re--writing that code spring already implemented. You may ask someone from spring-security team how you can tap into the current spring-security config defined by user, and call for authentication. Other stuff should be handled by Spring-security. This is, of course, case for VaadinSharedSecurity.

What do you think ?

**Comment by peholmst** [comment]
Trying to reuse as much as possible is a good goal. It's just that some parts of the Spring Security implementation cannot be directly applied to a Vaadin application, where there are not always any HTTP requests or responses, etc.

**Comment by gokhanoner** [comment]
Is it related to Vaadin PUSH or are there any other parts as well ??

**Comment by peholmst** [comment]
Yes, it has to do with websocket based Push. I'm still hoping there would be a way to integrate the websocket requests with Spring Security's filter chain, but I'm not sure if that is possible.

**Comment by gokhanoner** [comment]
This is added with Spring Security 4.0

http://docs.spring.io/spring-security/site/docs/current/reference/html/websocket.html

**Comment by peholmst** [comment]
We have to figure out how to get that integrated with Vaadin, then.

**Comment by gokhanoner** [comment]
I'm willing to help on that one, if needed.

**Comment by peholmst** [comment]
That would be much appreciated! A good starting point would then be to get Vaadin shared security to work properly with Web Sockets PUSH enabled.

**Comment by peholmst** [comment]
Reopening since there should be a more long term solution to this problem.

**Comment by peholmst** [comment]
I've been doing some digging here to try to reuse as much Spring Security code as possible, but it feels very hacky. Maybe I should just try to rethink everything instead. Especially the filters are causing trouble.

**Comment by peholmst** [comment]
I think we just have to go with our own implementation. Plugging into Spring's filter based approach just didn't feel right for a Vaadin application. Also, Spring Security's web socket support seems to be working with STOMP only and thus could not be used for Vaadin. I added an atmosphere interceptor that transfers the SecurityContext from the session to the web socket thread instead.
