### ISSUE TITLE
Doc eventbus subscribers held with weak references?

### ISSUE THREAD

**Issue by xenoterracide** [peholmst/vaadin4spring#256]
one of the major problems experienced with vaadin and eventbuses is that most eventbus systems hold strong references to the listeners leading to components not being able to be garbage collected asap.

when I subscribe to events how is the subscriber held? it would be nice to have that information added to this readme on it.

https://github.com/peholmst/vaadin4spring/blob/master/addons/eventbus/README.md

**Comment by peholmst** [comment]
I can update the README. There are plans to support weak references as well: #47
