### ISSUE TITLE
@UIScope view navigate listener ??

### ISSUE THREAD

**Issue by gokhanoner** [peholmst/vaadin4spring#259]
I have ```@UIScope``` views and I couldn't find a way to calla method when user navigate to that view ? My idea is to refresh the date ob the page when the user navigates. Is it possible ? (I'm using ```@VaadinSharedSecurity```, SideBar Menu etc., all auto configured)

**Comment by peholmst** [comment]
Can't you use the enter() method in your view (from https://vaadin.com/api/com/vaadin/navigator/View.html)?

**Comment by gokhanoner** [comment]
It only runs first time when u enter the view. After that, it doesnt fire.
Tested.

**Comment by peholmst** [comment]
And you have entered, left and then entered the view again?

**Comment by gokhanoner** [comment]
Yes.. But it didnt fired again. I supposr because wiew is already open in
the background, because of the uiscope, it just show how i left it.

**Comment by peholmst** [comment]
That's strange. The enter() method should fire every time a user navigates to the view, regardless of whether the instance is reused or not. I have to look into this. In the mean time, you could try overriding the attach() method and updating your view there.

**Comment by cropp** [comment]
I have had this issue before when I made the mistake of having a static in
my class.

Curtis

**Comment by gokhanoner** [comment]
Peter,

I'm closing the issue. You're right, enter() is working perfectly. I don't know how or when I tested list time.

Thanks.
