### ISSUE TITLE
Custom logout URL in managed security

### ISSUE THREAD

**Issue by peholmst** [peholmst/vaadin4spring#261]
Right now, when logging out using managed security, the current page will just get refreshed. Make it possible to customize this behavior.

**Comment by cropp** [comment]
I am using 0.7 release with vaadin shared spring security. With a a vaadin
logout handler and spring wired to use it on
.logout.handlerHandler(mybean).logoutUrl (/logout).

I would assume the same behavior could be defined in your vaadin logout
view. Call the vaadinSecurity.logout() then Page.getCurrent
().setLocation(somewhere)

From phone it's the best I can remember if the functions are not correct.
