### ISSUE TITLE
Vaadin 7/Standalone Tomcat 8 - NoSuchMethodError: org.vaadin.spring.security.shared.DefaultVaadinSharedSecurity.getRememberMeServices

### ISSUE THREAD

**Issue by Artgit** [peholmst/vaadin4spring#283]
I can't run my Spring Boot/Vaadin application on Standalone Tomcat 8.0.35 with a following exception:

    java.lang.NoSuchMethodError: org.vaadin.spring.security.shared.DefaultVaadinSharedSecurity.getRememberMeServices()Lorg/springframework/security/web/authentication/RememberMeServices;
    	at org.vaadin.spring.security.shared.DefaultVaadinSharedSecurity.getRememberMeParameter(DefaultVaadinSharedSecurity.java:101)
    	at org.vaadin.spring.security.shared.DefaultVaadinSharedSecurity.login(DefaultVaadinSharedSecurity.java:65)
    	at org.vaadin.spring.security.shared.DefaultVaadinSharedSecurity.login(DefaultVaadinSharedSecurity.java:164)

The same application perfectly runs on Embedded Tomcat.

This is my Security configuration:

    @Configuration
    @EnableWebSecurity
    @EnableVaadinSharedSecurity
    public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
    
    	@Autowired
    	private SocialAuthenticationSuccessHandler socialAuthenticationSuccessHandler;
    
    	@Autowired
    	private DBUserDetailsService userDetailsService;
    
    	@Value("${social.postLogin.url}")
    	private String postLoginUrl;
    
    	@Override
    	public void configure(WebSecurity web) throws Exception {
    		// @formatter:off
    		web.ignoring()
    			.antMatchers("/static/**")
    			.antMatchers("/VAADIN/**");
    		// @formatter:on
    	}
    
    	@Override
    	protected void configure(HttpSecurity http) throws Exception {
    
    		// @formatter:off
    		
    		// Set a custom successHandler on the SocialAuthenticationFilter
    		final SpringSocialConfigurer socialConfigurer = new SpringSocialConfigurer();
    		socialConfigurer.addObjectPostProcessor(new ObjectPostProcessor<SocialAuthenticationFilter>() {
    			@Override
    			public <O extends SocialAuthenticationFilter> O postProcess(O socialAuthenticationFilter) {
    				socialAuthenticationFilter.setAuthenticationSuccessHandler(socialAuthenticationSuccessHandler);
    				socialAuthenticationFilter.setPostLoginUrl(postLoginUrl);
    				return socialAuthenticationFilter;
    			}
    		});
    		
    		http
    			.csrf().disable() // Use Vaadin's built-in CSRF protection instead
    			.sessionManagement().sessionAuthenticationStrategy(sessionAuthenticationStrategy())
    		.and()
    			.httpBasic().disable()
    			.formLogin().disable()
    			.rememberMe().rememberMeServices(rememberMeServices()).key("myAppKey")
    		.and()
    			.logout()
    				.addLogoutHandler(new VaadinSessionClosingLogoutHandler()).logoutUrl("/logout")
    				.logoutSuccessUrl("/login?logout").permitAll()
    		.and()
    			.exceptionHandling().authenticationEntryPoint(new LoginUrlAuthenticationEntryPoint("/login"))
            //Configures url based authorization
            .and()
            	.authorizeRequests()
                	//Anyone can access the urls
            		.antMatchers("/login/**").anonymous()
            		.antMatchers("/vaadinServlet/UIDL/**").permitAll()
            		.antMatchers("/vaadinServlet/HEARTBEAT/**").permitAll()
    	            .antMatchers("/auth/**").permitAll()
    	            .antMatchers("/actuator/health").permitAll()
    	            .antMatchers("/actuator/**").hasAuthority("PERMISSION_READ_ACTUATOR_DATA")
    	            //.anyRequest().authenticated()
            //Adds the SocialAuthenticationFilter to Spring Security's filter chain.
            .and()
    			// apply the configuration from the socialConfigurer (adds the SocialAuthenticationFilter)
    			.apply(socialConfigurer);
    		
    		// @formatter:on
    	}
    
    	/**
    	 * The {@link RememberMeServices} must be available as a Spring bean for
    	 * Vaadin4Spring.
    	 */
    	@Bean
    	public RememberMeServices rememberMeServices() {
    		return new TokenBasedRememberMeServices("myAppKey", userDetailsService);
    	}
    
    	@Bean
    	public SessionAuthenticationStrategy sessionAuthenticationStrategy() {
    		return new SessionFixationProtectionStrategy();
    	}
    
    	@Bean(name = VaadinSharedSecurityConfiguration.VAADIN_AUTHENTICATION_SUCCESS_HANDLER_BEAN)
    	VaadinAuthenticationSuccessHandler vaadinAuthenticationSuccessHandler(HttpService httpService, VaadinRedirectStrategy vaadinRedirectStrategy) {
    		return new VaadinUrlAuthenticationSuccessHandler(httpService, vaadinRedirectStrategy, "/");
    	}
    
    	/**
    	 * Configures the authentication manager bean which processes authentication
    	 * requests.
    	 */
    	@Override
    	protected void configure(AuthenticationManagerBuilder auth) throws Exception {
    		auth.userDetailsService(userDetailsService).passwordEncoder(new BCryptPasswordEncoder());
    	}
    
    	@Override
    	@Bean
    	public AuthenticationManager authenticationManagerBean() throws Exception {
    		return super.authenticationManagerBean();
    	}
    
    }

In my war file I have `vaadin-spring-ext-security-0.0.7.RELEASE.jar` 

What can be wrong and how to solve this issue ?

**Comment by peholmst** [comment]
Thanks for the report. What other JAR files do you have in your WAR-file? I suspect this might be some kind of conflict between archives in the classpath.

**Comment by Artgit** [comment]
08.07.2015  20:50             4я467 aopalliance-1.0.jar
13.12.2015  17:11            53я231 asm-5.0.3.jar
18.10.2015  15:40           116я927 aspectjrt-1.8.7.jar
15.05.2016  13:45         1я864я922 aspectjweaver-1.8.9.jar
01.03.2016  20:30           773я825 atmosphere-runtime-2.2.7.vaadin1.jar
27.11.2015  20:35            73я869 cdi-api-2.0-EDR1.jar
12.08.2015  22:49            62я873 classmate-1.1.0.jar
17.05.2016  20:07           232я563 commons-beanutils-1.9.1.jar
06.01.2016  16:13           588я337 commons-collections-3.2.2.jar
08.07.2015  20:50           146я108 commons-digester-1.8.1.jar
08.07.2015  20:50           185я140 commons-io-2.4.jar
13.08.2015  19:25           434я678 commons-lang3-3.4.jar
08.07.2015  20:54            62я050 commons-logging-1.1.3.jar
20.02.2016  22:36           175я074 commons-validator-1.5.0.jar
14.10.2015  21:50           116я565 concurrentlinkedhashmap-lru-1.4.2.jar
17.05.2016  20:07            16я030 confirmdialog-2.1.1.jar
22.05.2016  17:07           157я259 domain-0.0.1.jar
26.02.2016  17:04            79я797 flute-1.3.0.gg2.jar
01.11.2015  08:23            43я067 gmetric4j-1.0.7.jar
22.05.2016  21:52            33я445 gofullscreen-addon-0.5.3.jar
17.05.2016  19:57            11я011 googleanalyticstracker-2.1.0.jar
20.05.2016  11:02           143я680 gridstack-addon-0.3.0.jar
04.03.2016  23:35           229я650 gson-2.6.2.jar
26.02.2016  17:05         2я306я492 guava-16.0.1.vaadin1.jar
08.10.2015  20:49         2я256я213 guava-18.0.jar
04.03.2016  23:34           704я465 hibernate-validator-5.2.4.Final.jar
04.03.2016  23:32            50я909 jackson-annotations-2.7.2.jar
04.03.2016  23:32           252я567 jackson-core-2.7.2.jar
04.03.2016  23:32         1я201я010 jackson-databind-2.7.2.jar
08.07.2015  20:50            73я063 javax.el-api-3.0.0.jar
08.07.2015  20:50             2я497 javax.inject-1.jar
08.07.2015  20:50            24я404 javax.interceptor-api-1.2.jar
12.08.2015  21:54            30я724 javax.transaction-api-1.2.jar
12.08.2015  22:49            66я711 jboss-logging-3.2.1.Final.jar
15.05.2016  13:46            16я431 jcl-over-slf4j-1.7.21.jar
15.05.2016  14:06           871я260 js-1.7R2.jar
03.09.2015  21:50           315я320 jsoup-1.8.3.jar
08.07.2015  20:50            15я071 jta-1.1.jar
15.05.2016  13:46             4я597 jul-to-slf4j-1.7.21.jar
15.05.2016  13:46            23я646 log4j-over-slf4j-1.7.21.jar
04.03.2016  23:32           291я373 logback-classic-1.1.6.jar
04.03.2016  23:32           460я961 logback-core-1.1.6.jar
08.07.2015  20:53         1я173я785 lucene-analyzers-3.6.2.jar
08.07.2015  20:53         1я539я086 lucene-core-3.6.2.jar
17.05.2016  20:07            86я138 maddon-1.15.jar
17.05.2016  20:07            62я874 markdown4j-2.2-cj-1.0.jar
01.11.2015  08:23           112я558 metrics-core-3.1.2.jar
01.11.2015  08:23             9я219 metrics-ganglia-3.1.2.jar
01.11.2015  08:23            20я852 metrics-graphite-3.1.2.jar
15.05.2016  13:47            22я805 neo4j-2.3.3.jar
15.05.2016  13:47            22я477 neo4j-advanced-2.3.3.jar
15.05.2016  13:47            82я333 neo4j-backup-2.3.3.jar
15.05.2016  13:47           356я521 neo4j-cluster-2.3.3.jar
15.05.2016  13:47           131я268 neo4j-codegen-2.3.3.jar
15.05.2016  13:47           148я917 neo4j-com-2.3.3.jar
15.05.2016  13:47           377я891 neo4j-consistency-check-2.3.3.jar
15.05.2016  13:47           327я695 neo4j-consistency-check-legacy-2.3.3.jar
15.05.2016  13:47            70я587 neo4j-csv-2.3.3.jar
15.05.2016  13:47         1я160я572 neo4j-cypher-2.3.3.jar
26.07.2015  16:35         2я986я228 neo4j-cypher-compiler-1.9_2.11-2.0.5.jar
01.11.2015  08:23        10я404я861 neo4j-cypher-compiler-2.2_2.11-2.2.6.jar
15.05.2016  13:47         8я852я564 neo4j-cypher-compiler-2.3-2.3.3.jar
08.07.2015  20:53            92я797 neo4j-cypher-dsl-2.0.1.jar
15.05.2016  13:47         3я414я733 neo4j-cypher-frontend-2.3-2.3.3.jar
15.05.2016  13:47            31я953 neo4j-enterprise-2.3.3.jar
15.05.2016  13:47            50я241 neo4j-enterprise-kernel-2.3.3.jar
15.05.2016  13:47            66я369 neo4j-function-2.3.3.jar
15.05.2016  13:47           183я299 neo4j-graph-algo-2.3.3.jar
15.05.2016  13:47            55я596 neo4j-graph-matching-2.3.3.jar
15.05.2016  13:47           310я583 neo4j-ha-2.3.3.jar
15.05.2016  13:47           128я779 neo4j-io-2.3.3.jar
15.05.2016  13:47            46я758 neo4j-jmx-2.3.3.jar
15.05.2016  13:47         3я397я380 neo4j-kernel-2.3.3.jar
15.05.2016  13:47            75я516 neo4j-logging-2.3.3.jar
15.05.2016  13:47           236я615 neo4j-lucene-index-2.3.3.jar
15.05.2016  13:47            60я689 neo4j-management-2.3.3.jar
15.05.2016  13:47            78я101 neo4j-metrics-2.3.3.jar
15.05.2016  13:47           197я028 neo4j-primitive-collections-2.3.3.jar
15.05.2016  13:47            22я657 neo4j-query-logging-2.3.3.jar
15.05.2016  13:47            37я794 neo4j-udc-2.3.3.jar
15.05.2016  13:47            28я297 neo4j-unsafe-2.3.3.jar
28.07.2015  19:54         1я202я373 netty-3.6.3.Final.jar
01.11.2015  08:23            87я603 oncrpc-1.0.7.jar
08.07.2015  20:53            19я827 opencsv-2.3.jar
08.07.2015  20:53           186я607 parboiled-core-1.1.7.jar
26.07.2015  16:37           233я224 parboiled-scala_2.11-1.1.7.jar
11.07.2015  01:25            15я808 sac-1.3.jar
14.10.2015  21:49         5я745я606 scala-library-2.11.7.jar
14.10.2015  21:49           423я753 scala-parser-combinators_2.11-1.0.4.jar
14.10.2015  21:49         4я576я443 scala-reflect-2.11.7.jar
04.03.2016  23:32            40я518 slf4j-api-1.7.18.jar
27.11.2015  19:56           269я579 snakeyaml-1.16.jar
15.05.2016  13:45           371я197 spring-aop-4.2.6.RELEASE.jar
15.05.2016  13:45            58я363 spring-aspects-4.2.6.RELEASE.jar
15.05.2016  13:45           731я562 spring-beans-4.2.6.RELEASE.jar
15.05.2016  13:46           548я397 spring-boot-1.3.5.RELEASE.jar
15.05.2016  13:46           449я763 spring-boot-actuator-1.3.5.RELEASE.jar
15.05.2016  13:46           757я978 spring-boot-autoconfigure-1.3.5.RELEASE.jar
15.05.2016  13:46             2я218 spring-boot-starter-1.3.5.RELEASE.jar
15.05.2016  13:46             2я198 spring-boot-starter-actuator-1.3.5.RELEASE.jar
15.05.2016  13:46             2я253 spring-boot-starter-logging-1.3.5.RELEASE.jar
15.05.2016  13:46             2я229 spring-boot-starter-security-1.3.5.RELEASE.jar
15.05.2016  13:46             2я283 spring-boot-starter-social-facebook-1.3.5.RELEASE.jar
15.05.2016  13:46             2я292 spring-boot-starter-social-linkedin-1.3.5.RELEASE.jar
15.05.2016  13:46             2я281 spring-boot-starter-social-twitter-1.3.5.RELEASE.jar
15.05.2016  13:46             2я243 spring-boot-starter-validation-1.3.5.RELEASE.jar
15.05.2016  13:46             2я226 spring-boot-starter-web-1.3.5.RELEASE.jar
15.05.2016  13:45         1я096я730 spring-context-4.2.6.RELEASE.jar
15.05.2016  13:45         1я096я425 spring-core-4.2.6.RELEASE.jar
04.03.2016  23:30           638я920 spring-data-commons-1.11.4.RELEASE.jar
04.03.2016  23:30           517я940 spring-data-neo4j-3.4.4.RELEASE.jar
15.05.2016  13:45           262я993 spring-expression-4.2.6.RELEASE.jar
15.05.2016  13:46           473я345 spring-security-config-4.0.4.RELEASE.jar
27.11.2015  19:57           357я249 spring-security-core-4.0.3.RELEASE.jar
01.11.2015  08:25            43я255 spring-security-crypto-3.2.8.RELEASE.jar
22.05.2016  15:35           354я629 spring-security-web-4.1.0.RELEASE.jar
19.12.2015  11:27            27я720 spring-social-config-1.1.4.RELEASE.jar
27.11.2015  20:34           123я879 spring-social-core-1.1.4.RELEASE.jar
19.12.2015  11:28           236я461 spring-social-facebook-2.0.3.RELEASE.jar
08.07.2015  20:54            34я858 spring-social-github-1.0.0.M4.jar
08.07.2015  20:54           135я714 spring-social-google-1.0.0.RELEASE.jar
02.10.2015  20:41           265я490 spring-social-linkedin-1.0.2.RELEASE.jar
27.11.2015  20:34            32я362 spring-social-security-1.1.4.RELEASE.jar
27.11.2015  19:56           182я982 spring-social-twitter-1.1.2.RELEASE.jar
27.11.2015  20:34            44я118 spring-social-web-1.1.4.RELEASE.jar
15.05.2016  13:45           265я182 spring-tx-4.2.6.RELEASE.jar
15.05.2016  19:09            48я098 spring-vaadin-0.0.5.RELEASE.jar
15.05.2016  19:09            32я433 spring-vaadin-eventbus-0.0.5.RELEASE.jar
15.05.2016  19:09             4я396 spring-vaadin-mvp-0.0.5.RELEASE.jar
15.05.2016  19:09            29я035 spring-vaadin-security-0.0.5.RELEASE.jar
15.05.2016  13:45           767я148 spring-web-4.2.6.RELEASE.jar
15.05.2016  13:45           877я630 spring-webmvc-4.2.6.RELEASE.jar
26.02.2016  17:04            39я547 streamhtmlparser-jsilver-0.0.10.vaadin1.jar
21.05.2016  12:42            97я981 vaadin-autocompletetextfield-1.0-alpha-4.jar
15.05.2016  14:19           955я235 vaadin-client-compiled-7.6.6.jar
15.05.2016  14:06           402я082 vaadin-push-7.6.6.jar
15.05.2016  14:06           532я600 vaadin-sass-compiler-0.9.13.jar
15.05.2016  14:06         3я469я526 vaadin-server-7.6.6.jar
15.05.2016  14:06         2я383я371 vaadin-shared-7.6.6.jar
01.03.2016  20:30            34я900 vaadin-slf4j-jdk14-1.6.1.jar
26.02.2016  17:04            48я511 vaadin-spring-1.0.0.jar
01.03.2016  20:30            35я219 vaadin-spring-addon-eventbus-0.0.7.RELEASE.jar
01.03.2016  20:30            11я020 vaadin-spring-addon-i18n-0.0.7.RELEASE.jar
01.03.2016  20:30            38я726 vaadin-spring-addon-sidebar-0.0.7.RELEASE.jar
26.02.2016  17:04            11я498 vaadin-spring-boot-1.0.0.jar
26.02.2016  17:04             1я862 vaadin-spring-boot-starter-1.0.0.jar
01.03.2016  20:30            10я607 vaadin-spring-ext-boot-0.0.7.RELEASE.jar
01.03.2016  20:30            19я670 vaadin-spring-ext-core-0.0.7.RELEASE.jar
01.03.2016  20:30            45я866 vaadin-spring-ext-security-0.0.7.RELEASE.jar
15.05.2016  14:07         7я620я025 vaadin-themes-7.6.6.jar
08.07.2015  20:53            63я777 validation-api-1.1.0.Final.jar
15.05.2016  14:06           787я509 yuicompressor-2.4.8.jar

**Comment by peholmst** [comment]
I notice you're mixing jars from 0.0.5 and 0.0.7, including the security jar. This is the problem.

**Comment by Artgit** [comment]
I have fixed my classpath and now this issue has now been resolved! Thank you!

**Comment by peholmst** [comment]
You're welcome, I'm glad it works! :-)
