### ISSUE TITLE
Vaadin 7 + Spring Boot error page

### ISSUE THREAD

**Issue by Artgit** [peholmst/vaadin4spring#285]
I have integrated Vaadin 7 and Spring Boot. Right now I need to implement error view in order to substitute standard page, for example:

    Whitelabel Error Page
    
    This application has no explicit mapping for /error, so you are seeing this as a fallback.
    Mon May 23 10:50:20 EEST 2016
    There was an unexpected error (type=Forbidden, status=403).
    Access is denied

It should be implemented as a separated Vaadin UI or in some other way ? Could you please provide me with an implementation of such page ? Thanks.

**Comment by christoph-frick** [comment]
See [Custom error pages](http://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference/htmlsingle/#boot-features-error-handling-custom-error-pages)

**Comment by Artgit** [comment]
What is the best practice with Vaadin 7 - do I need to implemented it as a separated Vaadin UI with Error view or use other approaches like html/jsp.. etc pages ?

**Comment by christoph-frick** [comment]
above error message (looks to me) like a standard spring boot error message.  so in this case vaadin might not even be involved. an error view is used by the navigator, if there is no view for a name. so the best practice for some customer facing application is to have all of it set up properly (container, spring, vaadin, ...)

**Comment by peholmst** [comment]
In projects where we are using standard Spring Security with filtered web security, we've used Velocity pages for login, logout and error and themed them so that they have the same look and feel as the Vaadin application. In other applications, we've only used Spring Security on the backend layer and handled everything ourselves within the Vaadin application.

**Comment by Artgit** [comment]
Thanks !
