### ISSUE TITLE
spring-boot-sample-security does not work yet?

### ISSUE THREAD

**Issue by bagerman** [peholmst/vaadin4spring#29]
Hi,
I am trying to run spring-boot-sample-security in eclipse / tomcat to no avail. At the same time, I am getting a prompt for user id and password while running it as an "application" via main() call. Unfortunately it does not take "user"/"password" :-(
Is it still work in progress or am i doing something wrong?
Thanks
Alex

**Comment by dhhabi** [comment]
security.login(username.getValue(), password.getValue());

For me : login method is undefined 

I am not sure what I am missing here.

**Comment by christoph-frick** [comment]
@dhhabi are you using `java.security.Security` instead the one from spring?

**Comment by dhhabi** [comment]
It only Shows two options :
java.security.Security
import org.springframework.boot.actuate.autoconfigure.ManagementServerProperties.Security;

May be i am missing some dependency. ?

**Comment by dvperv** [comment]
@dhhabi 

I used `@Autowired AuthenticationManager authenticationManager;` instead, but Vaadin expects return as JSON, but return is HTML page and communication error happens.

@VaadinUI is not found, @SpringUI instead
