### ISSUE TITLE
Vaadin 8 support

### ISSUE THREAD

**Issue by zotona** [peholmst/vaadin4spring#297]
Do you planned  to support 8 version. When it happen?

**Comment by christoph-frick** [comment]
Since you already have opened a ticket in the gradle plugin: what problems do you face?  There is the 2.0 snapshot of the official spring plugin too.

**Comment by zotona** [comment]
i have used a vaadin-spring-ext-security
i think what something breaks in servlet. Because i always get a 
``Failed to load the bootstrap javascript: ./VAADIN/vaadinBootstrap.js?v=8.0-SNAPSHOT``

**Comment by aley2003** [comment]
We are developing an application with vaadin-bom:8.0-SNAPSHOT and vaadin-spring-boot-starter:2.0-SNAPSHOT. To use vaadin4spring we had to change the vaadin4spring pom.xml (build source/target, vaadin.version, vaadin-spring.version, spring-boot.version) and compile it for Vaadin 8.
Can you please create a Vaadin 8 branch/release? This would be very helpfull for all trying to develop Vaadin 8 applications.

**Comment by jonmartinsolaas** [comment]
Yup, Vaadin 8 is now released, support would be very nice, especially in the sidebar addon.

**Comment by darkwitch** [comment]
I've created a PR for that https://github.com/peholmst/vaadin4spring/pull/303

**Comment by mstahv** [comment]
Has somebody used the latest master with Vaadin 8? Any apparent issues? I think we should cut a release for V8 soon.

**Comment by jonmartinsolaas** [comment]
using it in a small project, not seen any issues.

**Comment by FearlessHyena** [comment]
Since #303 added this and there's been a release already this can probably be closed
