### ISSUE TITLE
cant download from maven repository, cant find jars, what should i do?

### ISSUE THREAD

**Issue by gravin** [peholmst/vaadin4spring#309]
[INFO] Building Vaadin4Spring Samples - Side Bar 2.0.1-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The POM for org.vaadin.spring.extensions:vaadin-spring-ext-boot:jar:2.0.1-SNAPSHOT is missing, no dependency information available
[WARNING] The POM for org.vaadin.spring.addons:vaadin-spring-addon-sidebar:jar:2.0.1-SNAPSHOT is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] Vaadin4Spring Samples .............................. SUCCESS [  0.171 s]
[INFO] Vaadin4Spring Samples - Side Bar ................... FAILURE [  0.343 s]
[INFO] Vaadin4Spring Samples - Event Bus .................. SKIPPED
[INFO] Vaadin4Spring Samples - Push ....................... SKIPPED
[INFO] Vaadin4Spring Samples - Vaadin Managed Security .... SKIPPED
[INFO] Vaadin4Spring Samples - Vaadin Shared Security ..... SKIPPED
[INFO] Vaadin4Spring Samples - Navigation ................. SKIPPED
[INFO] Vaadin4Spring Samples - I18N ....................... SKIPPED

**Comment by jonmartinsolaas** [comment]
clone and build 2.0.1-snap locally, its not in the repo.

**Comment by mstahv** [comment]
Yes, only releases are in central. No 2.0.1-SNAPSHOST is yet built to snapshot repository, if using samples, build the whole project form top level first.
