### ISSUE TITLE
Useful code for Vaadin4Spring - not applicable directly to code base without work

### ISSUE THREAD

**Issue by code-monk** [peholmst/vaadin4spring#31]
I can feedback some of the work I've done integrating vaadin4spring into a non Spring Boot based project, however some of it would be better implemented in the vaadin4spring framework itself rather than wrapping classes.
Some of it isn't applicable depending on what is needed (e.g entity manager per request) however this could give some ideas and pointers for issues people have, but it wouldn't be a full example (i.e. not like the examples given in this project).
Is there somewhere I can upload this code for improvement/future integration?

**Comment by peholmst** [comment]
@code-monk A lot has happened with the add-on since March last year. Is this ticket still relevant? Is there any code you'd still like to see integrated into the add-on?

**Comment by peholmst** [comment]
I'm closing this ticket. Please reopen or create a new one if needed.
