### ISSUE TITLE
Security only works in MODE_GLOBAL

### ISSUE THREAD

**Issue by sddakoty** [peholmst/vaadin4spring#50]
Hi,

the security on a vaadin application using Navigator and @Secured annotations only works if the following is set:

	@PostConstruct
	public void init() {
	     SecurityContextHolder.setStrategyName(SecurityContextHolder.MODE_GLOBAL);
	}

Problem: if running on a webserver, mode_global is of course not the right strategy, as then no user specific authentication context will exist.
Though, if using any other strategy, the Authentication object is often null when a @VaadinView is changed.

**Comment by GJRTimmer** [comment]
If you would eliminate the SecurityContextHolder then you can not use the SpringSecurityFilterChain. Access to the ```Authentication``` object is now implemented by ```VaadinSecurity```.

Within your UI you can autowire the ```VaadinSecurity``` which should give you all the access you need, also as provided with the samples, the SpringSecurityFilterChain is now used so your ```Authentication``` object is always populated. If not populated with an authenticated user, the filter chain will populate it with a anonymous ```Authentication``` object.

Example
```java
@Autowired
private VaadinSecurity security;
```

Issue Closed
