### ISSUE TITLE
Support for @Push-Annotion?

### ISSUE THREAD

**Issue by stenersen** [peholmst/vaadin4spring#51]
Will the @Push-Annotion be supported for UIs? Right now the sample application does not start when i enable Push-Support. In my application (running in Tomcat) the server starts but the scopes get messed up.

**Comment by sbradeen** [comment]
Just to be clear, is 'server.sessionTimeout' not the same as 'server.session-timeout' ? And what are the time units?

**Comment by peholmst** [comment]
server.sessionTimeout should be the same as server.session-timeout. And the time units is seconds.

**Comment by peholmst** [comment]
See #169

**Comment by peholmst** [comment]
See #209 #203

**Comment by peholmst** [comment]
Closing since this is no longer relevant to Vaadin4Spring. Any issues should be reported to the official Vaadin Spring add-on project.
