### ISSUE TITLE
Move EventBus to separate module?

### ISSUE THREAD

**Issue by peholmst** [peholmst/vaadin4spring#60]
Would it be a good idea to move the EventBus to a separate module and enable it when needed?

**Comment by GJRTimmer** [comment]
```EventBus``` => #144 

About ```SpringViewProvider``` & ```VaadinView```
Is it an idea to move ```SpringViewProvider```, ```VaadinView``` and both *-mvp artifacts into a new artifact => spring-vaadin-navigator ?

Does this makes sense ?

**Comment by peholmst** [comment]
Closing this ticket in favor of #144. Let's keep the navigation stuff where it is until #147 is done.
