### ISSUE TITLE
Cannot debug with restartApplication

### ISSUE THREAD

**Issue by fastnsilver** [peholmst/vaadin4spring#61]
If after making some change to code, and I want to restart the Vaadin application to test it out without having to stop and restart the Spring Boot app itself, with:

`?debug&restartApplication` to my URL

I get

 `java.lang.illegalstateexception:%20Session%20has%20already%20been%20set.%20Old%20session:%20com.vaadin.server.VaadinSession@1cf357f4%20for%20springAwareVaadinServlet.%20New%20session:%20com.vaadin.server.VaadinSession@2c136305%20for%20springAwareVaadinServlet.`

**Comment by peholmst** [comment]
This task might be transferred to the official add-on team once the first version of the Vaadin official Spring add-on is released.

**Comment by peholmst** [comment]
Does not apply to Vaadin4Spring any more. If this is still a problem, report it here: http://dev.vaadin.com/
