### ISSUE TITLE
Create separate README for spring-vaadin and spring-boot-vaadin

### ISSUE THREAD

**Issue by peholmst** [peholmst/vaadin4spring#65]
Create separate README files for the Maven modules.

**Comment by mcumbay** [comment]
Is there any documentation/example on how to use this addon using Spring (no Spring Boot)?

**Comment by peholmst** [comment]
No, not yet. There will be, but I don't know when yet.

**Comment by peholmst** [comment]
Closed; spring-vaadin and spring-boot-vaadin are no more.
