### ISSUE TITLE
Update main README

### ISSUE THREAD

**Issue by peholmst** [peholmst/vaadin4spring#68]
Now when releases will start to show up in Maven central, the main README needs to be updated.

**Comment by GJRTimmer** [comment]
@peholmst What kind of update are you thinking about? Can you give me an other github project as an example reference which direction you want to persue.

**Comment by peholmst** [comment]
I just want to make sure that all the information required to be able to use this add-on is easily available in the READMEs and that the READMEs are up to date.

**Comment by GJRTimmer** [comment]
Agreed, I will make time soon to give the security-update README an overhaul.

**Comment by GJRTimmer** [comment]
@peholmst What do you think about the idea to cleanup all README to contain only relevant project information and move a lot of the configuration explanation to the project Wiki ? Just a thought.

**Comment by peholmst** [comment]
I'm afraid that having the documentation split up between READMEs and the wiki would result in the wiki always being out-of-date. If possible, I'd like to keep the documentation short and included with the sources. More extensive examples and/or tutorials could go into the wiki, though.

**Comment by GJRTimmer** [comment]
Good, I will keep the basic documentation about spring-security within the README, if more extensive documentation is required I will create a wiki page for vaadin-spring-security.
