### ISSUE TITLE
Vaadin 7 + Spring security configuration

### ISSUE THREAD

**Issue by Artgit** [peholmst/vaadin4spring#78]
Hello,

first of all - thank you so much for the awesome vaadin4spring add-on! I used it to configure spring with my existing vaadin application.

But right now I run into the problem while trying to configure Spring security with vaadin.

Also, I'm unable to correctly launch spring-boot-sample-security and continuously getting white screen in the my browser without any errors.

Could someone please take a look into my issue described here  http://stackoverflow.com/questions/25952514/vaadin-7-spring-security-configuration

What I'm doing wrong ?

**Comment by enyachoke** [comment]
@GJRTimmer  Thanks It solved it

**Comment by GJRTimmer** [comment]
Spring boot based security sample is now available. Located within the samples directory.

Note: This is a multi UI security sample with a fully working springSecurityFilterChain. 

Next update of the security-sample will be the implementation of 'remember-me' through the use of the official RememberMeAuthenticationFilter within the springSecurityFilterChain.

When this is completed the creation of a security-sample 'single-UI' will be started.

Anyone interested in helping out?

**Comment by GJRTimmer** [comment]
Basic implementation of Spring-Security is done. See [samples/security-sample](https://github.com/peholmst/vaadin4spring/tree/master/samples/security-sample)
