### ISSUE TITLE
Data Source sharing between Vaadin & Spring

### ISSUE THREAD

**Issue by nfrankel** [peholmst/vaadin4spring#92]
I've tried to wrap the provided Spring Boot's DataSource in a J2EEConnectionPool and it seems Vaadin faces SQLRecoverableException with "Closed Connection" labels.

For me, the fix was to replace the default data source with my own bean that does a JNDI lookup in the application server.

I'd suggest either fixing the issue or at least providing this workaround in the documentation.

**Comment by peholmst** [comment]
I'll leave this open for now, but I suspect the problem is with Spring Boot and not the Vaadin add-on.

**Comment by nfrankel** [comment]
I didn't have time to re-check.

**Comment by peholmst** [comment]
Closing since there has not been any activity for many months.
